name: Automatic Publish Github Package Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Package [adc.framework]
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1

      - name: Set up JDK 12.0
        uses: actions/setup-java@v1
        with:
          java-version: 12.0

      - name: Build with Gradle
        run: gradle build

      - name: Publish to GitHub Packages
          run: gradle publish
          env:
            GITHUB_USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_PUBLISH_PACKAGE_TOKEN }}

      - name: Publish Complete
        if: success()
        run: echo "adc.framework Packages Publish Success."
